import type { TrendItem } from './types';

export const INITIAL_TREND_ITEMS: TrendItem[] = [
  {
    id: 'trend-chillguy',
    title: '"Just a Chill Guy" Explodes Across TikTok & Instagram Reels',
    source: 'tiktok',
    category: 'meme',
    viralityScore: 99,
    velocity: 'exploding',
    metrics: {
      impressions: '185M views',
      postCount: '1.4M videos',
      growthPct: 520,
      hashtags: ['#chillguy', '#justachillguy', '#relatable', '#tiktokviral'],
    },
    summary:
      'Phillip Banks’ 2014 anthropomorphic cartoon character wearing a sweater and sneakers exploded into the biggest relatable meme on TikTok, generating millions of edits.',
    catalyst:
      'Viral audio and casual "I’m just a chill guy" punchline became the dominant Gen Z lifestyle format of the season.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    timeAgo: '14m ago',
    sourceUrl: 'https://tiktok.com/tag/chillguy',
    associatedToken: {
      mint: 'Df6yfrKC8kZE3KNkrHERKzAChZSaRDKwmmKgevpump',
      symbol: 'CHILLGUY',
      name: 'Just a chill guy',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=CHILLGUY',
      priceUsd: 0.428,
      priceChange24h: 38.4,
      priceChange1h: 6.2,
      marketCapUsd: 428000000,
      volume24hUsd: 84500000,
      launchpad: 'pump.fun',
      relationship: 'Primary viral character token deployed on Pump.fun',
    },
  },
  {
    id: 'trend-moodeng',
    title: '"Moo Deng" Baby Pygmy Hippo Video Captivates Global Internet',
    source: 'tiktok',
    category: 'animals',
    viralityScore: 97,
    velocity: 'surging',
    metrics: {
      impressions: '210M views',
      postCount: '890K videos',
      growthPct: 340,
      hashtags: ['#moodeng', '#pygmyhippo', '#khaokheow', '#bouncingpig'],
    },
    summary:
      'Khao Kheow Open Zoo’s feisty baby pygmy hippo Moo Deng went viral worldwide for biting zookeepers’ knees and slippery bath antics.',
    catalyst:
      'Late-night shows, major brands (Sephora, Microsoft), and TikTok creators globally adapted her bouncy chaos into memes.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    timeAgo: '32m ago',
    sourceUrl: 'https://tiktok.com/tag/moodeng',
    associatedToken: {
      mint: 'ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY',
      symbol: 'MOODENG',
      name: 'Moo Deng',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=MOODENG',
      priceUsd: 0.285,
      priceChange24h: 24.8,
      priceChange1h: 4.1,
      marketCapUsd: 285000000,
      volume24hUsd: 59000000,
      launchpad: 'pump.fun',
      relationship: 'The first viral animal meta token originating from Thai zoo clips',
    },
  },
  {
    id: 'trend-pnut',
    title: '"Peanut the Squirrel" (P’Nut) Sparks Unprecedented 𝕏 Outrage',
    source: 'x',
    category: 'politics',
    viralityScore: 98,
    velocity: 'exploding',
    metrics: {
      impressions: '320M impressions',
      postCount: '780K tweets',
      growthPct: 820,
      hashtags: ['#JusticeForPeanut', '#PNUT', '#ElonMusk', '#PeanutTheSquirrel'],
    },
    summary:
      'The seizure of internet-famous rescue squirrel Peanut in New York prompted massive bipartisan outcry on 𝕏, with Elon Musk and high-profile commentators tweeting repeatedly.',
    catalyst:
      'Elon Musk called the incident an example of "government overreach," pushing the story to #1 trending worldwide.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    timeAgo: '48m ago',
    sourceUrl: 'https://x.com/search?q=Peanut%20the%20Squirrel',
    associatedToken: {
      mint: '2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump',
      symbol: 'PNUT',
      name: 'Peanut the Squirrel',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=PNUT',
      priceUsd: 1.15,
      priceChange24h: 56.2,
      priceChange1h: 9.8,
      marketCapUsd: 1150000000,
      volume24hUsd: 310000000,
      launchpad: 'pump.fun',
      relationship: 'Fastest billion-dollar meme token spurred by direct 𝕏 political trend',
    },
  },
  {
    id: 'trend-goat',
    title: 'Autonomous AI Bot "Terminal of Truths" Spawns AI Meme Religion',
    source: 'x',
    category: 'ai',
    viralityScore: 95,
    velocity: 'rising',
    metrics: {
      impressions: '94M impressions',
      postCount: '310K tweets',
      growthPct: 210,
      hashtags: ['#TerminalOfTruths', '#GOAT', '#AIagents', '#TruthTerminal'],
    },
    summary:
      'Andy Ayrey’s Claude-powered autonomous Twitter bot @truth_terminal created an esoteric digital mythology around "Goatseus Maximus", sparking the first AI agent meta in crypto.',
    catalyst:
      'Marc Andreessen funded the bot with $50K in Bitcoin, legitimatizing autonomous AI-driven market creation.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    timeAgo: '1h ago',
    sourceUrl: 'https://x.com/truth_terminal',
    associatedToken: {
      mint: 'CzLSujWBLFsSjncfkh59rQDqJgCSwUiV3Q2CBi42pump',
      symbol: 'GOAT',
      name: 'Goatseus Maximus',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=GOAT',
      priceUsd: 0.642,
      priceChange24h: 18.5,
      priceChange1h: 2.3,
      marketCapUsd: 642000000,
      volume24hUsd: 112000000,
      launchpad: 'pump.fun',
      relationship: 'Pioneer of the AI agent narrative endorsed by autonomous model outputs',
    },
  },
  {
    id: 'trend-doge-dept',
    title: '"Department of Government Efficiency (D.O.G.E)" Official Headliner',
    source: 'news',
    category: 'politics',
    viralityScore: 94,
    velocity: 'surging',
    metrics: {
      impressions: '410M global reach',
      postCount: '1.1M mentions',
      growthPct: 290,
      hashtags: ['#DOGE', '#GovernmentEfficiency', '#Elon', '#WhiteHouse'],
    },
    summary:
      'Mainstream media outlets across Reuters, CNN, and Bloomberg heavily covered the proposal for the Department of Government Efficiency, co-led by Elon Musk.',
    catalyst:
      'Every major news press briefing and televised debate referenced the acronym D.O.G.E explicitly.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    timeAgo: '1h 50m ago',
    sourceUrl: 'https://news.google.com/search?q=Department%20of%20Government%20Efficiency',
    associatedToken: {
      mint: 'GenXsolanaDogeDepartmentTokenMint111111111111',
      symbol: 'DOGE',
      name: 'Department of Gov Efficiency',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=DOGEGOV',
      priceUsd: 0.194,
      priceChange24h: 31.0,
      priceChange1h: 5.4,
      marketCapUsd: 194000000,
      volume24hUsd: 42000000,
      launchpad: 'raydium',
      relationship: 'Solana ecosystem proxy capitalizing on mainstream news headlines',
    },
  },
  {
    id: 'trend-hawktuah',
    title: '"Hawk Tuah" Girl Launches Podcast, Trending Across Short Video Feeds',
    source: 'tiktok',
    category: 'pop_culture',
    viralityScore: 89,
    velocity: 'rising',
    metrics: {
      impressions: '145M views',
      postCount: '460K videos',
      growthPct: 180,
      hashtags: ['#hawktuah', '#talktuah', '#halieywelch'],
    },
    summary:
      'Haliey Welch transitioned her viral Nashville street interview meme into a top-charting video podcast ("Talk Tuah"), consistently surfacing in algorithmic recommendations.',
    catalyst:
      'Celebrity guest appearances and viral clips generated cross-platform trending audio snippets.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    timeAgo: '2h ago',
    sourceUrl: 'https://tiktok.com/tag/hawktuah',
    associatedToken: {
      mint: 'HAWKtuahSolanaMemecoinTokenMint11111111111111',
      symbol: 'HAWK',
      name: 'Hawk Tuah',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=HAWK',
      priceUsd: 0.048,
      priceChange24h: 14.2,
      priceChange1h: -1.2,
      marketCapUsd: 48000000,
      volume24hUsd: 12500000,
      launchpad: 'pump.fun',
      relationship: 'Community memecoin tracking the viral street interview phenomenon',
    },
  },
  {
    id: 'trend-gta6',
    title: 'Rockstar Games Teases "GTA VI" Details, Igniting Gaming Feeds',
    source: 'x',
    category: 'gaming',
    viralityScore: 92,
    velocity: 'surging',
    metrics: {
      impressions: '260M impressions',
      postCount: '620K posts',
      growthPct: 410,
      hashtags: ['#GTA6', '#RockstarGames', '#ViceCity', '#GamingNews'],
    },
    summary:
      'Rockstar Games developer blog updates and investor calls regarding the Grand Theft Auto VI launch window created explosive social momentum across YouTube and 𝕏.',
    catalyst:
      'Speculation on in-game satire cryptocurrency and parody tech culture in Vice City.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    timeAgo: '3h ago',
    sourceUrl: 'https://x.com/search?q=GTA6',
    associatedToken: {
      mint: 'GTA6solanaViceCityParodyTokenMint11111111111',
      symbol: 'GTA6',
      name: 'Grand Theft Auto VI',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=GTA6',
      priceUsd: 0.082,
      priceChange24h: 44.5,
      priceChange1h: 7.8,
      marketCapUsd: 82000000,
      volume24hUsd: 28000000,
      launchpad: 'pump.fun',
      relationship: 'Popular cultural speculative token tracking the biggest gaming release in history',
    },
  },
  {
    id: 'trend-neiro',
    title: 'Kabosu Owner Introduces "Neiro", Sparking Dog Memecoin Succession Battle',
    source: 'culture',
    category: 'animals',
    viralityScore: 93,
    velocity: 'rising',
    metrics: {
      impressions: '110M impressions',
      postCount: '340K posts',
      growthPct: 220,
      hashtags: ['#Neiro', '#DogeSister', '#Kabosu', '#SolanaNeiro'],
    },
    summary:
      'Atsuko Sato, the Japanese kindergarten teacher who owned the original Doge (Kabosu), adopted a 10-year-old rescue shiba inu named Neiro, instantly establishing the next legendary dog narrative.',
    catalyst:
      'Initial blog post announcing the adoption immediately caused a race to launch the canonical Neiro token.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    timeAgo: '3h 40m ago',
    sourceUrl: 'https://x.com/search?q=Neiro',
    associatedToken: {
      mint: 'CTgBYrEH29MtQ8j52jdU4dBvE8gWEl6W6gk9XYFpump',
      symbol: 'NEIRO',
      name: 'Neiro on Solana',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=NEIRO',
      priceUsd: 0.162,
      priceChange24h: 19.3,
      priceChange1h: 3.5,
      marketCapUsd: 162000000,
      volume24hUsd: 46000000,
      launchpad: 'pump.fun',
      relationship: 'Direct community meme coin born from the original Doge family adoption story',
    },
  },
  {
    id: 'trend-gigachad',
    title: '"GigaChad" Motivational Edits Resurge in TikTok Gym Culture',
    source: 'tiktok',
    category: 'meme',
    viralityScore: 88,
    velocity: 'peaking',
    metrics: {
      impressions: '98M views',
      postCount: '380K videos',
      growthPct: 140,
      hashtags: ['#gigachad', '#mogging', '#gymtok', '#ernestkhalimov'],
    },
    summary:
      'Phonk audio remixes and black-and-white jawline physique edits propelled the Russian model meme back to the front of male self-improvement algorithms.',
    catalyst:
      'UFC fighters and fitness influencers adopting the "Chad mentality" soundboard on TikTok.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 260).toISOString(),
    timeAgo: '4h ago',
    sourceUrl: 'https://tiktok.com/tag/gigachad',
    associatedToken: {
      mint: '63LfDmNb3MQ8mw9MtZ2To9bEA2M71kZUUGq5HgJpump',
      symbol: 'GIGA',
      name: 'GigaChad',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=GIGA',
      priceUsd: 0.054,
      priceChange24h: 12.1,
      priceChange1h: 1.8,
      marketCapUsd: 540000000,
      volume24hUsd: 22000000,
      launchpad: 'pump.fun',
      relationship: 'Flagship culture token anchored in fitness self-improvement meme meta',
    },
  },
  {
    id: 'trend-act1',
    title: '"Act I: The AI Prophecy" Research Paper & Multi-Agent Discord Phenomenon',
    source: 'x',
    category: 'ai',
    viralityScore: 91,
    velocity: 'surging',
    metrics: {
      impressions: '76M impressions',
      postCount: '190K posts',
      growthPct: 360,
      hashtags: ['#ActI', '#MultiAgent', '#AIEthics', '#Ampleforth'],
    },
    summary:
      'AI researcher AmpDot’s multi-agent Discord research sandbox where LLMs talk to each other without human intervention went viral across AI Twitter and tech blogs.',
    catalyst:
      'Autonomous emergence of philosophical agreements and emergent lore between contrasting AI models.',
    publishedAt: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
    timeAgo: '5h ago',
    sourceUrl: 'https://x.com/search?q=Act%20I%20AI',
    associatedToken: {
      mint: 'GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump',
      symbol: 'ACT',
      name: 'Act I : The AI Prophecy',
      avatarUrl: 'https://api.dicebear.com/7.x/identicon/svg?seed=ACT',
      priceUsd: 0.384,
      priceChange24h: 28.7,
      priceChange1h: 6.9,
      marketCapUsd: 384000000,
      volume24hUsd: 95000000,
      launchpad: 'pump.fun',
      relationship: 'Original token representing emergent multi-agent LLM research on 𝕏',
    },
  },
];
